### PR TITLE
added google verification to html page

### PR DESCRIPTION
**Pull request by mashhoodr**
This was added for verifying the domain on Youtube so we can add site links to the videos

### CODE REVIEW

**Comment by afirdousi** [comment]
👍

**Comment by afirdousi** [comment]
Since CI is not yet in place, I will have to deploy it manually on digital ocean. Will do it tonight.

**Comment by afirdousi** [comment]
Deployed. It's live now.

**Comment by mashhoodr** [comment]
@afirdousi gracious! Let me know if I should configure TravisCI for testing and deployment for this project - I will just need access to the droplet I think.

**Pull request merged**
